DROP TABLE IF EXISTS QUOTES;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS PROJECTS;
DROP TABLE IF EXISTS QUESTIONS_AND_ANSWERS;

CREATE TABLE QUOTES (
  ID           INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PRESENTATION CLOB                               NOT NULL
);
CREATE TABLE CATEGORIES (
  ID   INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME CLOB                               NOT NULL
);
CREATE TABLE PROJECTS (
  ID          INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME        CLOB                               NOT NULL,
  DESCRIPTION CLOB                               NOT NULL,
  CATEGORY_ID INTEGER                            NOT NULL,
  COST        INTEGER,
  BALANCE     INTEGER,
  DEAD_LINE    CLOB,
  VIDEO_LINK   CLOB,
  HISTORY     CLOB
);
CREATE TABLE QUESTIONS_AND_ANSWERS (
  ID         INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  QUESTION   CLOB                               NOT NULL,
  ANSWER     CLOB,
  PROJECT_ID INTEGER                            NOT NULL
);
