CREATE TABLE QUOTES (id SERIAL PRIMARY KEY, name VARCHAR(200) NOT NULL UNIQUE);
INSERT INTO QUOTES (name) VALUES ('Quote1');
INSERT INTO QUOTES (name) VALUES ('Quote2');
INSERT INTO QUOTES (name) VALUES ('Quote3');