INSERT INTO reward (amount, reward, project_id)

VALUES 
(1,'DIGITAL SINGLE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(5,'THANK YOU!',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(10,'DIGITAL DOWNLOAD',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(15,'DIGITAL PLUS',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(25,'CD PLUS',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(35,'MORE MUSIC PLEASE!',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(50,'AUTOGRAPHED DOUBLE CD + FLOBOTS PATCH +YOUR NAME ON A POSTER + BONUS FOOTAGE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(65,'AUTOGRAPHED DOUBLE ALBUM + SONGBOOK',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(75,'PREMIUM T-SHIRT PACKAGE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(85,'PREMIUM VINYL PACKAGE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(100,'LISTENING PARTY PACKAGE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(150,'FULL FLOBOTS',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(200,'PRODUCER PACKAGE',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(250,'WHOSE BEATS?',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(300,'THE SHIRT OFF MY BACK ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(500,'BRER RABBIT’S CIGAR BOX OF WISDOM',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(1000,'FLOBOTS-ORIGINS LISTENING PARTY ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(1500,'CUSTOMIZED WORKSHOP ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(2020,'GUEST LIST THROUGH 2020 ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(3000,'FLOBOTS\' SINGING TELEGRAM ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(5000,'ACOUSTIC HOUSE PARTY ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"')),
(10000,'THE BIKE ',  
(select id from project where name='Flobots\' TWO NEW ALBUMS for 2016 "NOENEMIES"'));