package ua.com.goit.gojava7.kickstarter.model;

public enum MenuOptions {
	SHOW_MAIN_MENU, SHOW_CATEGORIES, SHOW_PROJECTS_IN_SPECIFIC_CATEGORY, SHOW_SPECIFIC_PROJECT, DONATE_TO_PROJECT, ADD_PAYMENT_SYSTEM_TO_ACCOUNT, EXIT
}
