package kickstarter.mvc.interfaces;

public enum IndexOfPage {
	CATEGORIES, 
	PROJECTS,
	DETAILED_PROJECT,
	ERROR_PAGE,
	END_PAGE,
	COMMENT_PAGE,
	INVEST_PAGE,
	DONATE_PAGE,
	BANK_OPERATION_RESULT_PAGE,
	APPLY_TRANSACTION_PAGE,
	REPOSITORY_MENU_PAGE;

}
